Cargo.toml, src/group.rs, src/lib.rs, src/scalar.rs
This PR adds a `Scalar` struct and basic arithmetic operations for `Element` and `Scalar`
Next steps:
=> feat: add Scalar struct and arithmetic operations

src/lib.rs
Going forward we should think about whether or not (or more realistically, to
what degree) we want to expose this stuff in the public API, but this is used
by the Elligator functionality now and doesn't add any additional API surface
over the existing Fr re-export.
=> Re-export Fq as well as Fr.

Cargo.toml, src/lib.rs
This lets them be unified with the ones used by `poseidon377`.
=> Update arkworks crates, particularly ark-ff, to 0.3 

src/group.rs
This inserts a nice hex-encoded string, rather than a long list of bytes or the raw internal field elements.
=> Improve Debug output for Element and Encoding.

src/lib.rs
Going forward, we should probably settle on a common scalar type.
=> Export the `Scalar` type so that scalar mul is accessible.

Cargo.toml, src/lib.rs
We need to export this parameter struct in general for proof support and in particular for https://github.com/penumbra-zone/penumbra/issues/711 since the [`KZG10`](https://docs.rs/ark-poly-commit/latest/ark_poly_commit/kzg10/struct.KZG10.html#impl) polynomial commitment scheme needs a `PairingEngine`
=> export `Bls12_377` parameter struct (implements `PairingEngine`)

src/encoding.rs
This will simplify using the `Element` type embedded in domain types that need protobuf serialization.
=> Add `TryFrom`/`From` impls to `Element` for byte slice types

sqrt_alg.sage
Noted during audit, this corrects our Sage spec to use the same method as the Rust code when we correct the result from the Sarkar algorithm for non-square inputs. The corresponding spec change is in [#1245](https://github.com/penumbra-zone/penumbra/pull/1245)
=> sage: unify method for correcting results for non-square inputs in square root algorithm

src/elligator.rs
* convert directly to projective instead of going to affine first
* renames hash-to-group public methods. I've marked the old ones as deprecated and we can remove them completely once the next testnet is released
=> hash-to-group changes from audit

src/r1cs.rs, src/r1cs/element.rs, src/r1cs/inner.rs, src/r1cs/lazy.rs, src/r1cs/ops.rs
The `ElementVar` now holds a `LazyElementVar` internally which holds the encoding (as an FqVar), element (allocated in R1CS), or both. This will be used in https://github.com/penumbra-zone/penumbra/pull/1772/files#diff-15e9dad302da95dcfddd6dfed54b570d900614d4cd6b06c07a93acd40b79d622R122
=> refactor: add `LazyElementVar`

src/r1cs/element.rs
Followup to #42. When we are doing compress to field, we should not pass through to the inner `Element`, instead we should be calling `LazyElementVar::encoding()` to fetch the `FqVar` if already has been created, and only calling `Element::compress_to_field()` if it doesn't exist.
=> fix: call `LazyElementVar::encoding` when doing compress to curve

src/r1cs.rs, src/r1cs/element.rs, src/r1cs/inner.rs, tests/groth16_gadgets.rs
This change expects `ElementVar` public inputs to always be allocated from the compressed representation (i.e. an `Fq`)
Towards https://github.com/penumbra-zone/penumbra/issues/2041
Smoke tests now pass when https://github.com/penumbra-zone/penumbra/pull/2046 is built using this branch
=> fix: rework encoding of public inputs

CHANGELOG.md, Cargo.toml, README.md
For https://github.com/penumbra-zone/penumbra/issues/2124
Note that this adds a default feature - "std" - which turns on the default "std" feature from the ark-std crate: https://github.com/arkworks-rs/std/blob/v0.3.0/Cargo.toml#L22
The other two features here are:
* `parallel`: turns on parallelism when using r1cs gadgets
* `r1cs`: just enables r1cs gadgets _without_ turning on parallelism
=> disable default internal parallelism (rayon)

CHANGELOG.md, Cargo.toml, src/r1cs/fqvar_ext.rs
There is an unnecessary loop in the decaf377 element's sign checks in R1CS, which adds an additional 7 constraints (so this is a circuit-breaking change).
=> r1cs: remove unnecessary loop in sign check

src/encoding.rs, tests/groth16_gadgets.rs
This PR:
* adds a `negate` method to the OOC `Element`
* adds a test checking consistency between the OOC and R1CS element negation
=> add negate method to Element

src/r1cs/inner.rs, src/r1cs/ops.rs, tests/groth16_gadgets.rs
=> fix: R1CS `SubAssign` and `AddAssign`

src/encoding.rs
**Title**: Fix no_std Compatibility in Serialization/Deserialization
**Body**:
Encountered a compilation issue when building the crate with no_std support using:
```bash
cargo build --no-default-features
```
**Errors**:
1. An error conversion issue with `?`, where `std::io::Error` could not be converted to `SerializationError`.
2. A trait bound error indicating that `W: ark_serialize::Write` was not satisfied.
**Resolution**:
Resolved these issues by substituting `std::io::Write`/`Read` traits with equivalent traits provided by `ark-serialize`. This change ensures compatibility with no_std targets, maintaining the crate's functionality while extending its usability in no_std environments.
=> Use ark-serialize reexports for the Write and Read Traits

.github/workflows/rust.yml, CHANGELOG.md, Cargo.toml, src/element.rs, src/element/affine.rs, src/element/projective.rs, src/encoding.rs, src/error.rs, src/invsqrt.rs, src/lib.rs, src/r1cs.rs, src/r1cs/element.rs, src/r1cs/inner.rs, src/r1cs/lazy.rs, src/r1cs/ops.rs, src/serialize.rs, tests/encoding.rs
After #58 I went to add `cargo-nono` to CI and discovered a number of places where there are `no_std` incompatibilities, this PR aims to resolve those
Towards https://github.com/penumbra-zone/penumbra/issues/3512
=> fix `no_std` incompatibility

.github/workflows/rust.yml, Cargo.toml
Closes #70
This adds a job that builds on a platform (`thumbv7em-none-eabihf`) without `std` or `alloc`. I had to make a couple of small dependency changes (see commits) to get successful compilation.
=> ci: add job building with no alloc feature

src/fields/fq.rs
=> Implement a checked conversion from bytes method in Fq

.github/workflows/rust.yml
The longest running CI jobs are the test suite, predictably. Before this change, runtimes were:
* 26m for r1cs
* 1h26m for r1cs,u32_backend
The other, non-test-suite jobs are all sub-minute, likely due to caching. To get runtimes down, we:
* use larger buildjet runners with more vcpus
* switch from "cargo test" to "cargo nextest"
* update caching logic to use the astria helper (significantly more headroom on caches)
=> ci: use larger runners

.config/nextest.toml, .github/workflows/rust.yml, Cargo.toml, benches/sqrt.rs
We want to use the `--release` behavior, but doing so directly would disable evaluation of `debug_assert` lines, so we'll selectively override that one option.
Updates the "check" and "test" jobs to use the `--profile ci`. Also ensures that "check" covers all targets, including benchmarks, and accordingly cleans up an unused import in same.
=> ci: dedicated profile for release + debug_assert

benches/sqrt.rs, src/fields/fp/u32/wrapper.rs, src/fields/fp/u64/wrapper.rs, src/fields/fq/u32/wrapper.rs, src/fields/fq/u64/wrapper.rs, src/fields/fr/u32/wrapper.rs, src/fields/fr/u64/wrapper.rs, tests/encoding.rs
The rationale here is that we only want the existing methods of constructing field elements, including from bytes.
There's an argument in favor of adding a constructor which takes in 64 bit limbs and reduces mod order, but that doesn't strike me as particularly necessary.
=> Make raw constructors of field elements private

Cargo.toml
This PR introduces some adjustments to the `Cargo.toml` configuration to better align with the crate's compatibility and usage requirements, particularly focusing on the removal of the `tracing` dependency and the relocation of `anyhow` to dev-dependencies. These changes are motivated by the need to ensure compatibility with the `thumbv6m-none-eabi` target, which does not support atomic operations required by `tracing` and std/alloc. 
- **Removed `tracing` and `tracing-subscriber` Dependencies**: Due to incompatibility with the `thumbv6m-none-eabi` target, which lacks support for atomic operations, the `tracing` and `tracing-subscriber` dependencies have been removed. Besides that, the tracing dependencies are not used within the crate.
- **Relocated `anyhow` to Dev-Dependencies**: The …
=> adjust anyhow scope and remove unused dependencies

Cargo.toml, src/ark_curve/constants.rs, src/ark_curve/element.rs, src/ark_curve/element/projective.rs, src/ark_curve/mod.rs, src/fields/fp.rs, src/fields/fp/u32/wrapper.rs, src/fields/fp/u64/wrapper.rs, src/fields/fq.rs, src/fields/fq/u32/wrapper.rs, src/fields/fq/u64/wrapper.rs, src/fields/fr.rs, src/fields/fr/u32/wrapper.rs, src/fields/fr/u64/wrapper.rs, src/lib.rs, src/min_curve/element.rs, tests/encoding.rs, tests/groth16_gadgets.rs
Don't merge yet, but this serves as a convenient staging point for these changes.
Will eventually close #87.
=> Add missing methods as need for integrating the latest version of this crate

CHANGELOG.md, Cargo.toml, src/fields/fq.rs, src/fields/fq/u32/wrapper.rs, src/fields/fq/u64/wrapper.rs
This PR has the bits needed to complete https://github.com/penumbra-zone/poseidon377/pull/53
Closes #87.
=> add power impl and expose `Fq::from_montgomery_limbs`

src/min_curve/ops.rs
In the multiplication implementations for `Element`, we accidentally forgot to dereference the references, leading to an infinite loop, as each multiplication implementation would never descend down to the actual implementation.
=> Fix infinite loops in small backend curve operations
